### ISSUE TITLE
Running Regard3D programmatically?

### ISSUE THREAD

**Issue by donnemartin** [rhiestan/Regard3D#1]
First off, great project!

I'm curious if there is a way to interact with Regard3D without the GUI and run this programmatically?

I could probably look through the calls made for each step as you interact with the GUI and chain those together, but perhaps there might already be something in place.

**Comment by rhiestan** [comment]
Thanks!

No, Regard3D can't be run programmatically, and I don't plan to implement this feature. If you need it, use OpenMVG instead, which is a collection of command-line tools that can easily be scripted.
Regard3D is based on OpenMVG (https://github.com/openMVG/openMVG).

**Comment by donnemartin** [comment]
Thanks for the quick reply, closing this issue.
