### ISSUE TITLE
Always exactly ten matches

### ISSUE THREAD

**Issue by omgitsraven** [rhiestan/Regard3D#10]
I've noticed a weird behaviour with Regard3D that keeps it from being very useful and certainly SEEMS like it must be a bug: no matter how many photos I take, no matter what settings I choose in "compute matches", no matter what subject I'm shooting, in my "matching results", there is always EXACTLY ten pairs in the "matches" list (the lower half of the window).

I don't think it's just an interface issue, either: there's also always only ten listed in the "initial image pair for incremental method" pane of the "triangulation" window, and then the eventual results of the triangulation always seem to only cover the parts of the scene shown in those ten pairs, and not the rest of the photographs.

I'm pretty new to this, so it's possible that I'm doing something wrong, and the internal process is so vague and mysterious to me that it's possible I'm misjudging things like whether anything outside those ten pairs is included..... but at the very least, after tons of experimentation, this seemed weird enough to bring up here and ask if this is normal.

**Comment by pmoulon** [comment]
@omgitsraven Thank you for your feedback.

The message `ten listed in the "initial image pair for incremental method"` appear normally if the automatic pipeline is unable to find an initial reconstruction from a pair of frame.
Are you sure of your intrinsic data (focal length)?

BTW, if you want you can also process your dataset in OpenMVG.

**Comment by omgitsraven** [comment]
I haven't seen that message anywhere; there's nothing like that in the console or the results window.
![1](https://user-images.githubusercontent.com/8540042/30726415-b0e7d5a0-9f18-11e7-92f1-53584d7b092a.PNG)
I'm not completely sure of the intrinsic data—my camera(phone) is a Samsung Galaxy S7, and when I first imported the photos, there was a focal length of 4.2mm (presumably from the metadata), but there was NOT a sensor width.

I looked up the S7's camera specs online, but sources disagree about whether it's 1/2.5" (5.76) or 1/2.6" (5.5)... I went with 5.76, but entered 5.75 because I saw so many cameras with that value in the sensor database CSV and thought the difference might have been a rounding error on the website. I right-clicked a photo and did "set sensor width" and entered 5.75mm, and it was automatically applied to the rest.

Would 0.01mm make a big difference? Would 0.25mm make a big difference, in case it's actually a 1/2.6" and not a 1/2.5"? I've looked all over the internet—is there some source I should be able to use (or some test I can perform) to confirm with 100% certainty the exact sensor width? (I just looked up the 'Camera ID', it's a S5K2L1, which is listed on wikipedia as `~1/2.5"`… it seems like no-one's sure!)

**Comment by rhiestan** [comment]
Your observation is correct that in the Triangulation window, Regard3D only shows the 10 best image pairs. However later in the triangulation process all pictures are used.
And yes, I only saw it now, in the "Matching results" dialog it also shows only 10 image pairs, this is a small bug.
But be assured, all pictures are used for the triangulation! If not, then it is because some pictures do not have enough matches between the "good group" (the group of pictures with sufficient matches).
I suggest that you use some example pictures, for example the Sceaux data set, or the kermit data set from here:

https://sourceforge.net/projects/regard3d/files/Demo/OpenMVG/

Then you clearly see that all pictures are used.
Also, the triangulation result shows how many pictures are effectively used under "Cameras".

**Comment by omgitsraven** [comment]
Ahh, okay..!

I can understand why not all the matches are shown, the exponential growth would get pretty big pretty fast.... but maybe it should show more than just ten? And maybe it should indicate the total number of matches somewhere, so the fact that it's just a short list is clearer...

(It would also be nice if the short list could include at least one of each source photo, so you can tell whether there's a subject that ISN'T being matched well... Actually, maybe clicking a photo in the top half could show you a list of just pairs that include that photo in the bottom half?)

I'm still learning best practices for taking photos for photogrammetry, and I was hoping to use the matches to learn what sections require extra photographs, but I guess I can just infer that from the final mesh instead...

Thanks for your help!
