### ISSUE TITLE
Loading Image Infos is getting stuck

### ISSUE THREAD

**Issue by DJPlaya** [rhiestan/Regard3D#27]
Ive tried adding 25 UHD Images, the Programm listed them instantly and loaded the Image Info for some of them.
Some of the Images do not contain Information like the Camera Model, still the Programm is trying to get some from them which then results in the Programm blocking me from closing the Window with the Reason "Please wait until all image infos have been listed"

**Comment by rhiestan** [comment]
Adding pictures without EXIF info should not be a problem. Maybe you have a corrupt image? Please try to identify this image and remove it from the list.

**Comment by DJPlaya** [comment]
The image was okay, i cold open it without a problem. Strangely it worked after i converted it. Was an issue with the metadata of the pics i guess.

**Comment by cronin4392** [comment]
I am experincing this as well. I tried to remove all metadata from my images using imagemagick but it still didn't work.
