### ISSUE TITLE
Export of surface with texture doesn't work

### ISSUE THREAD

**Issue by rhiestan** [rhiestan/Regard3D#4]
Since version 0.9.1, exporting a surface with texture (obj) does not work anymore. The exported file is a valid obj file, but some parts are missing and the texture is not properly aligned.

**Comment by Bamwd5** [comment]
I am also experiencing this issue. Any timeline on a fix?

**Comment by rhiestan** [comment]
Unfortunately not, no.
But there is an easy workaround: You will find the obj file in the project folder of your project. The project tree and the folder tree are in parallel. Only remember to copy also the texture and material files.

**Comment by rhiestan** [comment]
This bug should be fixed with 0.9.2, please retest!
