### ISSUE TITLE
Sensor Database

### ISSUE THREAD

**Issue by MarcoMazzo** [rhiestan/Regard3D#8]
hi,
i've installed the latest version, but after creating a new project and selecting the pictures it not reconise the sensor size. I've tried both an existing camera and adding a new one. It seems isn't able to find the csv file.
any suggestion?
I've tried also to run it as administrator.
Thanks

**Comment by rhiestan** [comment]
Are you working on Windows or on Mac OS? If on Windows, does the registry entry
HKEY_CURRENT_USER\Software\hiesti.ch\Regard3D\CameraDBFileName
point to the correct file?

**Comment by MarcoMazzo** [comment]
Sorry, yes i'm working on Windows 10 and yes it is pointing on the right path...

**Comment by rhiestan** [comment]
What is the exact name of the camera maker and model? Can you please make a screenshot from the picture set dialog?

**Comment by MarcoMazzo** [comment]
First i've tried to add my phone in the database
Microsoft;Lumia 930;5.76
![2017-09-08 09_30_30-proprieta - wp_20170608_12_16_05_pro jpg](https://user-images.githubusercontent.com/7794058/30200734-704ba936-9478-11e7-905e-9a225ac4d927.png)

then i've tried with another camera that is already in the database, a Canon EOS 5D Mark II
![2017-09-08 09_28_56-sirecon](https://user-images.githubusercontent.com/7794058/30200739-7a3cff4e-9478-11e7-875a-3d5f3e3df501.png).

this is the regedit 
![2017-09-08 09_43_19-editor del registro di sistema](https://user-images.githubusercontent.com/7794058/30201222-3502dc4e-947a-11e7-8269-6e0daeb2c6ab.png)

this is the picture set with both camera models
![pic-set](https://user-images.githubusercontent.com/7794058/30201346-befae8e2-947a-11e7-8a14-34b798c20b70.png)

here the database in notepad++ and the file path in the system
![sensor_database csv canon](https://user-images.githubusercontent.com/7794058/30201548-761684fa-947b-11e7-8e04-587629de1966.png)
![sensor_database csv lumia](https://user-images.githubusercontent.com/7794058/30201549-76185794-947b-11e7-988a-29bc1cca1b6c.png)

**Comment by rhiestan** [comment]
This is very strange. The only thing that comes to mind is that the sensor_database.csv is corrupted somehow. Can you please send it to me?

**Comment by MarcoMazzo** [comment]
i try to download from github
here is mine
[sensor_database.zip](https://github.com/rhiestan/Regard3D/files/1287187/sensor_database.zip)

**Comment by MarcoMazzo** [comment]
ok i solved downloading the csv from repository, the only thing i've done was modify it the first time with openoffice... maybe saving it i've corrupted the file.
Thanks for patience

**Comment by rhiestan** [comment]
OK, great! You're welcome!
